---

apiVersion: v1
kind: Secret
metadata:
  name: webrtc-gateway-secrets
  namespace: kamailio
type: Opaque
stringData:
  db-connection: postgres://postgres:fake@kamailio-db.kamailio.svc.cluster.local:5432/kamailio
