---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: b2bua
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - matrix:
        generators:

          # 1. Apps
          - git:
              repoURL: https://github.com/bundasmanu/gitops-infra
              revision: main
              files:
                - path: apps/b2bua.yml

          # 2. Clusters (chart_values_overrides in clusters/<name>/<app>.yml/overrides.yml)
          - git:
              repoURL: https://github.com/bundasmanu/gitops-infra
              revision: main
              files:
                - path: environments/*.yml

  template:
    metadata:
      name: "{{.name}}-{{.env}}"

    spec:
      project: default

      source:
        repoURL: "{{.repoURL}}"
        targetRevision: main
        path: "{{.chartPath}}"

        helm:
          values: |
            {{- $base := default (dict) (get . "chart_values") }}
            {{- $overrides := default (dict) (get . "chart_values_overrides") }}
            {{- $merged := merge (deepCopy $base) $overrides }}
            {{- toYaml $merged }}

      destination:
        name: '{{ index . "name-dest" }}'
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
