apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-kamailio
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/bundasmanu/gitops-infra
        revision: main
        files:
          - path: postgres-kamailio/*.yml

  template:
    metadata:
      name: "{{name}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/bundasmanu/postgres-kamailio-docker
        targetRevision: main
        path: helm/kamailio-db

        helm:
          parameters:
            - name: postgres_user
              value: "{{postgres_user}}"

            - name: postgres_password
              value: "{{postgres_password}}"

            - name: postgres_db
              value: "{{postgres_db}}"

      destination:
        name: in-cluster
        namespace: kamailio

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
