---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-kamailio
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bundasmanu/gitops-infra
        revision: main
        directories:
          - path: postgres-kamailio/*/*

  template:
    metadata:
      name: "{{name}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/bundasmanu/postgres-kamailio-docker
        targetRevision: main
        path: helm/kamailio-db
        helm:
          valueFiles:
            - values.yaml
            - ../../gitops-infra/postgres-kamailio/base/values.yaml
            - ../../gitops-infra/postgres-kamailio/{{path[1]}}/{{path[2]}}.yaml

      destination:
        name: in-cluster
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
